In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression


In [3]:
data=pd.read_csv('C:/Users/HP/Downloads/Sklearn.csv')
data

SAT   GPA
0   1714  2.40
1   1664  2.52
2   1760  2.54
3   1685  2.74
4   1693  2.83
..   ...   ...
79  1936  3.71
80  1810  3.71
81  1987  3.73
82  1962  3.76
83  2050  3.81

[84 rows x 2 columns]

In [4]:
x=data['SAT']
y=data['GPA']

In [33]:
xmat=x.values.reshape(-1,1) #to covert x into 2D matric
xmat.shape

(200, 1)

In [6]:

reg=LinearRegression()

In [7]:

reg.fit(xmat,y)

LinearRegression()

In [8]:
reg.score(xmat,y)

0.40600391479679765

In [9]:
reg.coef_

array([0.00165569])

In [10]:
reg.intercept_

0.2750402996602803

In [11]:
reg.predict([[1790]])

array([3.23872191])

In [12]:
new_data=pd.DataFrame(data=[1970,1230],columns=['SAT'])
new_data

SAT
0  1970
1  1230

In [13]:
new_data['Predict_GPA']=reg.predict(new_data)
new_data

C:\Users\HP\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


SAT  Predict_GPA
0  1970     3.536746
1  1230     2.311537

In [14]:
# Multiple leaner

In [15]:
data=pd.read_csv('C:/Users/HP/Downloads/reg2.csv')

In [16]:
x=data[['size','year']]
y=data['price']

In [17]:
reg=LinearRegression()

In [18]:
reg.fit(x,y)

LinearRegression()

In [19]:
reg.coef_

array([ 227.70085401, 2916.78532684])

In [20]:
reg.intercept_

-5772267.017463281

In [21]:
R2=reg.score(x,y)
R2

0.7764803683276793

In [22]:
x.shape

(100, 2)

In [23]:
n=x.shape[0]
p=x.shape[1]

AdjR=1-(1-R2)*(n-1)/(n-p-1)
AdjR

0.77187171612825

In [24]:
from sklearn.feature_selection import f_regression

In [25]:
f_regression(x,y)

(array([285.92105192,   0.85525799]), array([8.12763222e-31, 3.57340758e-01]))

In [26]:
pvalue=f_regression(x,y)[1]
pvalue

array([8.12763222e-31, 3.57340758e-01])

In [27]:
pvalue.round(3)

array([0.   , 0.357])

In [28]:
reg_summary=pd.DataFrame(data=x.columns.values,columns=['Feature'])

In [29]:
reg_summary['coefficients']=reg.coef_
reg_summary['P-values']=pvalue.round(3)

In [30]:
reg_summary

Feature  coefficients  P-values
0    size    227.700854     0.000
1    year   2916.785327     0.357